# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_remark_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemarkDialog(object):
    def setupUi(self, RemarkDialog):
        RemarkDialog.setObjectName("RemarkDialog")
        RemarkDialog.resize(400, 200)
        RemarkDialog.setMinimumSize(QtCore.QSize(400, 200))
        RemarkDialog.setMaximumSize(QtCore.QSize(400, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RemarkDialog.setWindowIcon(icon)
        self.remarkEditLine = QtWidgets.QLineEdit(RemarkDialog)
        self.remarkEditLine.setGeometry(QtCore.QRect(10, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.remarkEditLine.setFont(font)
        self.remarkEditLine.setText("")
        self.remarkEditLine.setObjectName("remarkEditLine")
        self.categoryComboBox = QtWidgets.QComboBox(RemarkDialog)
        self.categoryComboBox.setGeometry(QtCore.QRect(10, 50, 191, 31))
        self.categoryComboBox.setObjectName("categoryComboBox")
        self.tagListWidget = QtWidgets.QListWidget(RemarkDialog)
        self.tagListWidget.setGeometry(QtCore.QRect(210, 50, 181, 141))
        self.tagListWidget.setObjectName("tagListWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(RemarkDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 160, 195, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.buttonsLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.buttonsLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.saveButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.saveButton.setDefault(True)
        self.saveButton.setObjectName("saveButton")
        self.buttonsLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonsLayout.addWidget(self.cancelButton)

        self.retranslateUi(RemarkDialog)
        QtCore.QMetaObject.connectSlotsByName(RemarkDialog)

    def retranslateUi(self, RemarkDialog):
        _translate = QtCore.QCoreApplication.translate
        RemarkDialog.setWindowTitle(_translate("RemarkDialog", "Редактирование замечания"))
        self.remarkEditLine.setPlaceholderText(_translate("RemarkDialog", "Текст замечания"))
        self.categoryComboBox.setPlaceholderText(_translate("RemarkDialog", "Категория"))
        self.saveButton.setText(_translate("RemarkDialog", "Сохранить"))
        self.cancelButton.setText(_translate("RemarkDialog", "Отмена"))
